[package]
name = "simple-int"
version = "0.1.0"
authors = ["Nick Chapman <nic@amadido.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
